language: php
dist: trusty
sudo: required

cache:
  directories:
    - $HOME/.composer/cache/files

services:
  - docker

php:
  - 7.1

env:
  matrix:
    - JOB=job:check-coding-standards
    - JOB=job:run-unit-tests
    - JOB=job:run-behat-tests

install:
  - composer --verbose install

script:
  - vendor/bin/robo $JOB
